ALTER TABLE users ADD COLUMN IF NOT EXISTS sms_provider VARCHAR(20) DEFAULT 'TWILIO';
ALTER TABLE users ADD COLUMN IF NOT EXISTS smpp_host VARCHAR(255) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS smpp_port INT DEFAULT 2776;
ALTER TABLE users ADD COLUMN IF NOT EXISTS smpp_system_id VARCHAR(50) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS smpp_password VARCHAR(255) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS smpp_address_range VARCHAR(50) DEFAULT '';
